# lek 20
# docker compose up -d redis mongodb mysql postgres rabbitmq elasticsearch kibana notifications
# version: "3.9"
services:
  redis:
    container_name: redis_container
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning
    volumes:
      - ./docker-volumes/cache:/data

  # lek 22
  # https://hub.docker.com/_/mongo
  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./docker-volumes/data:/data/db

  # lek 23
  # https://hub.docker.com/_/mysql
  mysql:
    container_name: mysql_container
    image: mysql:latest
    # command: --default-authentication-plugin=mysql_native_password
    # command: --mysql-native-password=ON
    restart: always
    environment:
      - MYSQL_USER=freelancer_user
      - MYSQL_ROOT_PASSWORD=freelancer_pass
      - MYSQL_DATABASE=freelancer_auth
      - MYSQL_PASSWORD=freelancer_pass
      # - MYSQL_RANDOM_ROOT_PASSWORD=yes
    ports:
      - "3306:3306"
    volumes:
      - ./docker-volumes/mysql:/var/lib/mysql

  # lek 23
  # https://hub.docker.com/_/postgres
  postgres:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=freelancer
      - POSTGRES_PASSWORD=freelancer
      - POSTGRES_DB=freelancer_reviews
    ports:
      - "5432:5432"
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql

  # lek 24
  # https://hub.docker.com/_/rabbitmq
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:3.13-rc-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=freelancer
      - RABBITMQ_DEFAULT_PASS=freelancerpass
    ports:
      # AMQP protocol port
      - "5672:5672"
      # Management UI
      - "15672:15672"
    # new
    volumes:
      - ./docker-volumes/rabbitmq:/var/lib/rabbitmq
    networks:
      - elastic

  # lek 24 - 25
  # https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
  elasticsearch:
    container_name: elasticsearch_container
    # image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    restart: always
    environment:
      ES_JAVA_OPTS: -Xmx1g -Xms1g
      bootstrap.memory_lock: "true"
      discovery.type: single-node
      network.host: 0.0.0.0
      transport.host: 127.0.0.1
      http.host: 0.0.0.0
      # l. 283
      xpack.security.enabled: "true"
      # xpack.security.enabled: "false"
      xpack.security.authc.api_key.enabled: "true"
      xpack.monitoring.collection.enabled: "true"
      xpack.security.enrollment.enabled: "true"
      # l. 283
      xpack.security.authc.token.enabled: "true"
      ELASTIC_PASSWORD: admin1234
    ports:
      - 9300:9300
      - 9200:9200
    volumes:
      - ./docker-volumes/elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elastic

  # lek 26
  # https://www.elastic.co/guide/en/kibana/current/docker.html
  kibana:
    container_name: kibana_container
    image: docker.elastic.co/kibana/kibana:8.13.0
    # image: docker.elastic.co/kibana/kibana:8.11.0
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch_container:9200"]
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=kibana
      - ELASTICSEARCH_SERVICEACCOUNT_TOKEN=AAEAAWVsYXN0aWMva2liYW5hL2ZyZWVsYW5jZXIta2liYW5hOnpaVmJkX2tIVDZPNXRnWXVfNFdKUXc
      - XPACK_FLEET_AGENTS_ELASTICSEARCH_HOSTS=["http://elasticsearch_container:9200"]
    ports:
      - 5601:5601
    networks:
      - elastic
    volumes:
      - ./kibana.yml/:/usr/share/kibana/config/kibana.yml:ro
    depends_on:
      - elasticsearch

  # l. 285
  # https://www.elastic.co/guide/en/apm/guide/current/apm-quick-start.html
  # https://www.elastic.co/guide/en/observability/8.13/traces-get-started.html
  apmServer:
    image: docker.elastic.co/apm/apm-server:8.13.0
    container_name: apm_server_container
    ports:
      - 8200:8200
    volumes:
      - ./apm-server.yml:/usr/share/apm-server/apm-server.yml:ro
    networks:
      - elastic
    command: >
      apm-server -e
        -E apm-server.rum.enabled=true
        -E setup.kibana.host=kibana_container:5601
        -E setup.template.settings.index.number_of_replicas=0
        -E apm-server.kibana.enabled=true
        -E apm-server.kibana.host=kibana_container:5601
        -E apm-server.kibana.protocol=http
        -E strict.perms=false
        -E apm-server.auth.anonymous.enabled=true

  # l. 279
  metricbeat:
    container_name: metricbeat_container
    image: docker.elastic.co/beats/metricbeat:8.13.0
    user: root
    ports:
      - 5066:5066
    networks:
      - elastic
    volumes:
      - ./metricbeat.yml/:/usr/share/metricbeat/metricbeat.yml:ro
      # docker module
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # system module
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
      - /proc:/hostfs/proc:ro
      - /:/hostfs:ro
    command: ["--strict.perms=false", "-system.hostfs=/hostfs"]
    depends_on:
      - elasticsearch

  # l. 281
  heartbeat:
    container_name: heartbeat_container
    image: docker.elastic.co/beats/heartbeat:8.13.0
    user: root
    hostname: heartbeat
    cap_add:
      - NET_RAW
    networks:
      - elastic
    command: ["--strict.perms=false"]
    volumes:
      - ./heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro
    depends_on:
      - elasticsearch
  # lek 89
  gateway:
    container_name: gateway_container
    build:
      context: ../server/01-gateway-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4000:4000
    env_file: ../server/01-gateway-service/.env
    environment:
      - ENABLE_APM=0
      - GATEWAY_JWT_TOKEN=e03da812e3e0781558aa17a2299c0b4b
      - JWT_TOKEN=0195d39426913d078411557cf4257010
      - SECRET_KEY_ONE=0c6e59a0bea7247a180f74b444bdebbe
      - SECRET_KEY_TWO=5e56387684550eb2ca1d6b14d287001d
      - NODE_ENV=development
      - CLIENT_URL=http://localhost:3000
      - AUTH_BASE_URL=http://auth_container:4002
      - USERS_BASE_URL=http://localhost:4003
      - GIG_BASE_URL=http://localhost:4004
      - MESSAGE_BASE_URL=http://localhost:4005
      - ORDER_BASE_URL=http://localhost:4006
      - REVIEW_BASE_URL=http://localhost:4007
      - REDIS_HOST=redis://redis_container:6379
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200

      - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch

  #  lek 71
  notifications:
    container_name: notification_container
    build:
      context: ../server/02-notification-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4001:4001
    env_file: ../server/02-notification-service/.env
    environment:
      - ENABLE_APM=0
      - NODE_ENV=development
      - CLIENT_URL=http://localhost:3000
      - RABBITMQ_ENDPOINT=amqp://freelancer:freelancerpass@rabbitmq_container:5672
      - SENDER_EMAIL=karelle.moen@ethereal.email
      - SENDER_EMAIL_PASSWORD=cZn6mPdTSuBakUMTRg
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http:/apm_server_container:8200
      - ELASTIC_APM_SECRET_TOKEN=
      # - ELASTIC_APM_SECRET_TOKEN=thisismysecrettoken
      # - ELASTIC_APM_SECRET_TOKEN=cZn6mPdTSuBakUMTRg
    depends_on:
      - elasticsearch
    ## new
    # depends_on:
    #   - elasticsearch
    #   - rabbitmq
    # networks:
    #   - elastic

  # l. 132
  auth:
    container_name: auth_container
    build:
      context: ../server/03-auth-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4002:4002
    env_file: ../server/03-auth-service/.env
    environment:
      - ENABLE_APM=0
      - GATEWAY_JWT_TOKEN=e03da812e3e0781558aa17a2299c0b4b
      - JWT_TOKEN=0195d39426913d078411557cf4257010
      - NODE_ENV=development
      - API_GATEWAY_URL=http://gateway_container:4000
      - CLIENT_URL=http://localhost:3000
      - RABBITMQ_ENDPOINT=amqp://freelancer:freelancerpass@rabbitmq_container:5672
      - MYSQL_DB=mysql://freelancer_user:freelancer_pass@mysql_container:3306/freelancer_auth
      - CLOUD_NAME=dnt2ui6y0
      - CLOUD_API_KEY=459583183294839
      - CLOUD_API_SECRET=nA-ORtkwoggxgRAb_0J2SkWIlyc
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - mysql

  # l. 179
  users:
    container_name: users_container
    build:
      context: ../server/04-users-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4003:4003
    env_file: ../server/03-auth-service/.env
    environment:
      - ENABLE_APM=0
      - DATABASE_URL=mongodb://mongodb_container:27017/freelancer-users
      - GATEWAY_JWT_TOKEN=e03da812e3e0781558aa17a2299c0b4b
      - JWT_TOKEN=0195d39426913d078411557cf4257010
      - NODE_ENV=development
      - API_GATEWAY_URL=http://gateway_container:4000
      - CLIENT_URL=http://localhost:3000
      - RABBITMQ_ENDPOINT=amqp://freelancer:freelancerpass@rabbitmq_container:5672
      - CLOUD_NAME=dnt2ui6y0
      - CLOUD_API_KEY=459583183294839
      - CLOUD_API_SECRET=nA-ORtkwoggxgRAb_0J2SkWIlyc
      - REDIS_HOST=redis://redis_container:6379
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - mongodb

  # l. 217
  gig:
    container_name: gig_container
    build:
      context: ../server/05-gig-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4004:4004
    env_file: ../server/05-gig-service/.env
    environment:
      - ENABLE_APM=0
      - DATABASE_URL=mongodb://mongodb_container:27017/freelancer-gig
      - GATEWAY_JWT_TOKEN=e03da812e3e0781558aa17a2299c0b4b
      - JWT_TOKEN=0195d39426913d078411557cf4257010
      - NODE_ENV=development
      - API_GATEWAY_URL=http://gateway_container:4000
      - CLIENT_URL=http://localhost:3000
      - RABBITMQ_ENDPOINT=amqp://freelancer:freelancerpass@rabbitmq_container:5672
      - CLOUD_NAME=dnt2ui6y0
      - CLOUD_API_KEY=459583183294839
      - CLOUD_API_SECRET=nA-ORtkwoggxgRAb_0J2SkWIlyc
      - REDIS_HOST=redis://redis_container:6379
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - mongodb

  # l. 239
  chat:
    container_name: chat_container
    build:
      context: ../server/06-chat-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4005:4005
    env_file: ../server/06-chat-service/.env
    environment:
      - ENABLE_APM=0
      - DATABASE_URL=mongodb://mongodb_container:27017/freelancer-chat
      - GATEWAY_JWT_TOKEN=e03da812e3e0781558aa17a2299c0b4b
      - JWT_TOKEN=0195d39426913d078411557cf4257010
      - NODE_ENV=development
      - API_GATEWAY_URL=http://gateway_container:4000
      - CLIENT_URL=http://localhost:3000
      - RABBITMQ_ENDPOINT=amqp://freelancer:freelancerpass@rabbitmq_container:5672
      - CLOUD_NAME=dnt2ui6y0
      - CLOUD_API_KEY=459583183294839
      - CLOUD_API_SECRET=nA-ORtkwoggxgRAb_0J2SkWIlyc
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - mongodb

  # l. 264
  order:
    container_name: order_container
    build:
      context: ../server/07-order-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4006:4006
    env_file: ../server/07-order-service/.env
    environment:
      - ENABLE_APM=0
      - DATABASE_URL=mongodb://mongodb_container:27017/freelancer-order
      - GATEWAY_JWT_TOKEN=e03da812e3e0781558aa17a2299c0b4b
      - JWT_TOKEN=0195d39426913d078411557cf4257010
      - NODE_ENV=development
      - API_GATEWAY_URL=http://gateway_container:4000
      - CLIENT_URL=http://localhost:3000
      - RABBITMQ_ENDPOINT=amqp://freelancer:freelancerpass@rabbitmq_container:5672
      - STRIPE_API_KEY=
      - CLOUD_NAME=dnt2ui6y0
      - CLOUD_API_KEY=459583183294839
      - CLOUD_API_SECRET=nA-ORtkwoggxgRAb_0J2SkWIlyc
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - mongodb

  # l. 279
  review:
    container_name: service_container
    # container_name: review_container
    build:
      context: ../server/08-review-service
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 4007:4007
    env_file: ../server/08-review-service/.env
    environment:
      - ENABLE_APM=0
      - DATABASE_HOST=
      - DATABASE_USER=freelancer
      - DATABASE_PASSWORD=freelancerpass
      - DATABASE_NAME=freelancer_reviews
      - GATEWAY_JWT_TOKEN=e03da812e3e0781558aa17a2299c0b4b
      - JWT_TOKEN=0195d39426913d078411557cf4257010
      - NODE_ENV=development
      - API_GATEWAY_URL=http://gateway_container:4000
      - RABBITMQ_ENDPOINT=amqp://freelancer:freelancerpass@rabbitmq_container:5672
      - CLOUD_NAME=dnt2ui6y0
      - CLOUD_API_KEY=459583183294839
      - CLOUD_API_SECRET=nA-ORtkwoggxgRAb_0J2SkWIlyc
      - ELASTIC_SEARCH_URL=http://elastic:admin1234@elasticsearch_container:9200
      - ELASTIC_APM_SERVER_URL=http://apm_server_container:8200
      - ELASTIC_APM_SECRET_TOKEN=
    depends_on:
      - elasticsearch
      - postgres

  # l. 333
  jenkins:
    container_name: jenkins_container
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - ./docker-volumes/jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  # l. 333
  jenkins-agent:
    container_name: jenkins_agent_container
    image: jenkins/ssh-agent:jdk17
    privileged: true
    user: root
    expose:
      - 22
    # environment:
    #   - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCuxIi18e7FbWuMm6BgUoMRcAA5OXdW9hv1S+k7asB+Ih5e8kgXbPi5/1AYph2hrggUSAioZyWHRHOEILifgBmQDDD0g0Cgryx5EGBwV4kmsSY2x4qNDkXzFYHjBd4YQNHiUHAvQpXZvdTtaqRfzR4GZovofufKlo5D5+fZh/vpMEEKNdp+fLPdEQCovNg7xm7n3X9NUWSpnlPRLpi8YFu7sBOBJQY3TuUpePl3pWNxnTHFgjI1ctL/1HdUKPHHN+6jJsTxGyVIC3UG/4w8eTO5tE3WjQPG2gGoon2rH6quSVXAcaRvIFzbabCHGTiDdhDW8dH9YMjPJ9mJciiJ/rWSeb1NDfN/4fXGPkelIIIaXZQUF6gvT8wg1eqYVNcOqvoAbaX1xMaqelbpwNN2Va5BwzJXSVLEecy3SBmwCOtElIccaXvXu3wJyKQMvePr2jCDeeAbE1e7JkHllx1uH60e5/xYHfEh7qq7my83OsZpH8hjn3BZmeahPFXO0qXD3mM=
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIM5l8dUEMWjep94fpVxTslKfpvbDNpPo0IT6Sa3Zdso3 l@DESKTOP-BONUM-HP
networks:
  elastic:
    name: elastic
