# l. 303 d
apiVersion: apps/v1
kind: Deployment
metadata:
  name: f-postgres
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: f-postgres
  template:
    metadata:
      labels:
        app: f-postgres
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: f-postgres
          image: postgres:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRES_USER
              # value: freelancer
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: freelancer-postgres-user
            - name: POSTGRES_PASSWORD
              # value: freelancer
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: freelancer-postgres-password
            - name: POSTGRES_DB
              # value: freelancer_reviews
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: freelancer-postgres-db

            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          resources:
            limits:
              memory: "1Gi"
              cpu: "0.5"
            requests:
              cpu: 100m
              memory: 150Mi
          ports:
            - name: f-postgres
              containerPort: 5432
          volumeMounts:
            - name: postgres-local-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          readinessProbe:
            exec:
              command:
                [
                  "psql",
                  "-w",
                  "-U",
                  "freelancer",
                  "-d",
                  "freelancer_reviews",
                  "-c",
                  "SELECT 1",
                ]
            initialDelaySeconds: 120
            periodSeconds: 300
            timeoutSeconds: 60
          livenessProbe:
            exec:
              command:
                [
                  "psql",
                  "-w",
                  "-U",
                  "freelancer",
                  "-d",
                  "freelancer_reviews",
                  "-c",
                  "SELECT 1",
                ]
            initialDelaySeconds: 120
            periodSeconds: 300
            timeoutSeconds: 60
      volumes:
        - name: postgres-local-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
