# l. 311
apiVersion: v1
kind: Secret
metadata:
  name: freelancer-backend-secret
  namespace: production
type: Opaque
data:
  # echo -n <secret> | base64
  secret-key-one: MGM2ZTU5YTBiZWE3MjQ3YTE4MGY3NGI0NDRiZGViYmU=
  secret-key-two: NWU1NjM4NzY4NDU1MGViMmNhMWQ2YjE0ZDI4NzAwMWQ=
  gateway-jwt-token: ZTAzZGE4MTJlM2UwNzgxNTU4YWExN2EyMjk5YzBiNGI=
  jwt-token: MDE5NWQzOTQyNjkxM2QwNzg0MTE1NTdjZjQyNTcwMTA=
  sender-email: a2FyZWxsZS5tb2VuQGV0aGVyZWFsLmVtYWls
  sender-email-password: VjFobFpuQmhjMjFTTjJwNlpETnplV0pD
  cloud-name: ZG50MnVpNnkw
  cloud-api-key: NDU5NTgzMTgzMjk0ODM5
  cloud-api-secret: bkEtT1J0a3dvZ2d4Z1JBYl8wSjJTa1dJbHlj
  freelancer-redis-host: cmVkaXM6Ly86dGhpc2lzbXlvd25wYXNzd29yZDEyM0BAZi1yZWRpcy5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjYzNzk= # redis://:thisismyownpassword123@@f-redis.production.svc.cluster.local:6379
  # freelancer-redis-host: cmVkaXM6Ly86dGhpc2lzbXlvd25wYXNzd29yZDEyM0BAam9iYmVyLXJlZGlzLnByb2R1Y3Rpb24uc3ZjLmNsdXN0ZXIubG9jYWw6NjM3OQ==  # redis://:thisismyownpassword123@@jobber-redis.production.svc.cluster.local:6379
  freelancer-mysql-db: bXlzcWw6Ly9mcmVlbGFuY2VyX3VzZXI6ZnJlZWxhbmNlcl9wYXNzQGYtbXlzcWwucHJvZHVjdGlvbi5zdmMuY2x1c3Rlci5sb2NhbDozMzA2L2ZyZWVsYW5jZXJfYXV0aA== # mysql://freelancer_user:freelancer_pass@f-mysql.production.svc.cluster.local:3306/freelancer_auth
  # freelancer-mysql-db: bXlzcWw6Ly9qb2JiZXI6YXBpQGpvYmJlci1teXNxbC5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjMzMDYvam9iYmVyX2F1dGg=  mysql://jobber:api@jobber-mysql.production.svc.cluster.local:3306/jobber_auth
  freelancer-mysql-root-password: ZnJlZWxhbmNlcl9wYXNz # freelancer_pass
  freelancer-mysql-password: ZnJlZWxhbmNlcl9wYXNz # freelancer_pass
  freelancer-mysql-user: ZnJlZWxhbmNlcl91c2Vy # freelancer_user
  freelancer-mysql-db-name: ZnJlZWxhbmNlcl9hdXRo # freelancer_auth
  freelancer-postgres-host: Zi1wb3N0Z3Jlcy5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2Fs # f-postgres.production.svc.cluster.local
  # freelancer-postgres-host: am9iYmVyLXBvc3RncmVzLnByb2R1Y3Rpb24uc3ZjLmNsdXN0ZXIubG9jYWw= # jobber-postgres.production.svc.cluster.local
  freelancer-postgres-user: ZnJlZWxhbmNlcg== # freelancer
  # freelancer-postgres-user: am9iYmVy  # jobber
  freelancer-postgres-password: ZnJlZWxhbmNlcg== # freelancer
  # freelancer-postgres-password: YXBp  # api
  freelancer-postgres-db: ZnJlZWxhbmNlcl9yZXZpZXdz #  freelancer_reviews

  freelancer-rabbitmq-user: ZnJlZWxhbmNlcg== # freelancer
  freelancer-rabbitmq-password: ZnJlZWxhbmNlcnBhc3M= # freelancerpass

  freelancer-elasticsearch-password: YWRtaW4xMjM0 # admin1234
  freelancer-elasticsearch-username: ZWxhc3RpYw== # elastic
  stripe-api-key: c2tfdGVzdF81MVF5SlFJUlc0V1BtZ05DbjJjdEdPMW56M0JoeEVnMmpXVEtoVERmZlhoM1VGM2lzOW1lQ3NFZU9HSW93ZUc1RUlBbWplOFJCcTVRVkgzMldSOWJQU3B2UTAwTmdwakVVQVc= # Secret key
  stripe-client-key: cGtfdGVzdF81MVF5SlFJUlc0V1BtZ05DbjhTWmczYjd1Y0JXZkFDbHlDajJ3YUJxMmtGdlQ5TXlja0RYS3ZuQ2hxZTRvVDdPb0JBNzY4OVNENFZYNUxCYmxDUHZreVNLUjAwWGw5aDRkTFA= # Publishable key
  mongo-database-url: bW9uZ29kYjovL2YtbW9uZ28ucHJvZHVjdGlvbi5zdmMuY2x1c3Rlci5sb2NhbDoyNzAxNy9mcmVlbGFuY2Vy # mongodb://f-mongo.production.svc.cluster.local:27017/freelancer
  # mongo-database-url: bW9uZ29kYjovL2pvYmJlci1tb25nby5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3L2pvYmJlcg==  # mongodb://jobber-mongo.production.svc.cluster.local:27017/jobber
  freelancer-rabbitmq-endpoint: YW1xcDovL2ZyZWVsYW5jZXI6ZnJlZWxhbmNlcnBhc3NAZi1xdWV1ZS5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjU2NzI= # amqp://freelancer:freelancerpass@f-queue.production.svc.cluster.local:5672
  # freelancer-rabbitmq-endpoint: YW1xcDovL2pvYmJlcjpqb2JiZXJwYXNzQGpvYmJlci1xdWV1ZS5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjU2NzI=  # amqp://jobber:jobberpass@jobber-queue.production.svc.cluster.local:5672

  freelancer-elasticsearch-url: aHR0cDovL2VsYXN0aWM6YWRtaW4xMjM0QGYtZWxhc3RpYy5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2FsOjkyMDA= # http://elastic:admin1234@f-elastic.production.svc.cluster.local:9200

  # freelancer-elasticsearch-url: aHR0cDovL2VsYXN0aWM6YWRtaW4xMjM0QGpvYmJlci1lbGFzdGljLnByb2R1Y3Rpb24uc3ZjLmNsdXN0ZXIubG9jYWw6OTIwMA==  # http://elastic:admin1234@jobber-elastic.production.svc.cluster.local:9200
  freelancer-elastic-apm-server-url: ""
  # freelancer-elastic-apm-server-url: aHR0cDovL2YtYXBtLnByb2R1Y3Rpb24uc3ZjLmNsdXN0ZXIubG9jYWw6ODIwMA== # http://f-apm.production.svc.cluster.local:8200
  # freelancer-elastic-apm-server-url: aHR0cDovL2pvYmJlci1hcG0ucHJvZHVjdGlvbi5zdmMuY2x1c3Rlci5sb2NhbDo4MjAw  # http://jobber-apm.production.svc.cluster.local:8200
  freelancer-elastic-apm-secret-token: ""
  # freelancer-elastic-apm-secret-token: dGhpc2lzbXlzZWNyZXR0b2tlbg== # thisismysecrettoken
  freelancer-elasticsearch-host: Zi1lbGFzdGljLnByb2R1Y3Rpb24uc3ZjLmNsdXN0ZXIubG9jYWw= # f-elastic.production.svc.cluster.local


  # freelancer-elasticsearch-host: aHR0cDovL2YtZWxhc3RpYy5wcm9kdWN0aW9uLnN2Yy5jbHVzdGVyLmxvY2Fs # http://f-elastic.production.svc.cluster.local

  # freelancer-elasticsearch-host: am9iYmVyLWVsYXN0aWMucHJvZHVjdGlvbi5zdmMuY2x1c3Rlci5sb2NhbA==  # jobber-elastic.production.svc.cluster.local
