apiVersion: v1
kind: Service
metadata:
  name: freelancer-gig
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: freelancer-gig
  ports:
    - name: gig
      port: 4004
      targetPort: 4004
      protocol: TCP
