apiVersion: v1
kind: Service
metadata:
  name: freelancer-notifications
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: freelancer-notifications
  ports:
    - name: notifications
      port: 4001
      targetPort: 4001
      protocol: TCP
