# l. 315 a
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freelancer-order
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freelancer-order
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: freelancer-order
    spec:
      containers:
        - name: freelancer-order
          image: kreative358/freelancer-order:stable
          imagePullPolicy: Always
          resources:
            limits:
              memory: "1Gi"
              cpu: "0.5"
            requests:
              cpu: 100m
              memory: 150Mi
          ports:
            - name: order
              containerPort: 4006
          env:
            - name: ENABLE_APM
              value: "1"
            - name: NODE_ENV
              value: "production"
            - name: GATEWAY_JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: gateway-jwt-token
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: jwt-token
            - name: RABBITMQ_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: freelancer-rabbitmq-endpoint
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: mongo-database-url
            - name: CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: cloud-name
            - name: CLOUD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: cloud-api-key
            - name: CLOUD_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: cloud-api-secret
            - name: API_GATEWAY_URL
              value: "http://freelancer-gateway:4000"
            - name: CLIENT_URL
              # value: "https://freelancer-app.ovh"
              value: "http://localhost:3000"
            - name: STRIPE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: stripe-api-key
            - name: ELASTIC_SEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: freelancer-elasticsearch-url
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: freelancer-elastic-apm-server-url
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: freelancer-elastic-apm-secret-token
