# l. 299 b
apiVersion: v1
kind: Service
metadata:
  name: f-queue
  namespace: production
spec:
  type: ClusterIP
  selector:
    app: f-queue
  ports:
    - name: queue
      port: 5672
      targetPort: queue
      protocol: TCP
    - name: mgmt
      port: 15672
      targetPort: mgmt
      protocol: TCP
