apiVersion: apps/v1
kind: Deployment
metadata:
  name: freelancer-auth
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freelancer-auth
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: freelancer-auth
    spec:
      containers:
        - name: freelancer-auth
          image: kreative358/freelancer-auth:stable
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "0.5"
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 150Mi
          ports:
            - name: auth
              containerPort: 4002
          env:
            - name: ENABLE_APM
              value: "1"
            - name: NODE_ENV
              value: "production"
            - name: GATEWAY_JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: gateway-jwt-token
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: jwt-token
            - name: RABBITMQ_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: freelancer-rabbitmq-endpoint
            - name: MYSQL_DB
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: freelancer-mysql-db
            - name: CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: cloud-name
            - name: CLOUD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: cloud-api-key
            - name: CLOUD_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: cloud-api-secret
            - name: CLIENT_URL
              value: "https://freelancer-app.ovh"
              # value: "http://localhost:3000"
            - name: API_GATEWAY_URL
              value: "http://freelancer-gateway.production.svc.cluster.local:4000"
            - name: ELASTIC_SEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: freelancer-elasticsearch-url
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: freelancer-elastic-apm-server-url
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: freelancer-elastic-apm-secret-token
