# l. 314 a
apiVersion: apps/v1
kind: Deployment
metadata:
  name: freelancer-review
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: freelancer-review
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: freelancer-review
    spec:
      containers:
        - name: freelancer-review
          image: kreative358/freelancer-review:stable
          imagePullPolicy: Always
          resources:
            limits:
              memory: "1Gi"
              cpu: "0.5"
            requests:
              cpu: 100m
              memory: 150Mi
          ports:
            - name: review
              containerPort: 4007
          env:
            - name: ENABLE_APM
              value: "1"
            - name: NODE_ENV
              value: "production"
            - name: CLUSTER_TYPE
              value: "minikube"
            - name: GATEWAY_JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: gateway-jwt-token
            - name: JWT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: jwt-token
            - name: RABBITMQ_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: freelancer-rabbitmq-endpoint
            - name: DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: freelancer-postgres-host
            - name: DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: freelancer-postgres-user
            - name: DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: freelancer-postgres-password
            - name: DATABASE_NAME
              value: "freelancer_reviews"
            - name: CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: cloud-name
            - name: CLOUD_API_KEY
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: cloud-api-key
            - name: CLOUD_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: cloud-api-secret
            - name: API_GATEWAY_URL
              # value: "http://freelancer-gateway:4000"
              value: "http://freelancer-gateway.production.svc.cluster.local:4000"
            - name: ELASTIC_SEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: freelancer-elasticsearch-url
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: freelancer-elastic-apm-server-url
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: freelancer-backend-secret
                  key: freelancer-elastic-apm-secret-token
